---
- hosts: localhost
  gather_facts: False

  tasks: 
  - name: Create file log and Remove file log if an exist in localhost
    shell : rm -rf exim.txt; touch exim.txt


- hosts: cpanel
  no_log: true
  vars:
#        ansible_ssh_user: 'your_user'
#        ansible_port: 'your_port'
#        ansible_ssh_private_key_file: "/home/user/.ssh/id_rsa"
       limit: "1" #minimum want to display in log
  tags:
    - configuration
  gather_facts: False
  
  tasks:

   - name: Check exim using command (exim -bp)
     shell: exim -bp
     register: daxim
     
   - name: Server List 
     shell: echo "{{ inventory_hostname }}" | awk '{ print $1 }' | cut -d "." -f1
#     shell: echo "{{ inventory_hostname }}" 
     no_log: True
     register: server
     
#   - name: Show debugging on your fucking terminal
#     debug:
#      msg:
#       - "{{ daxim.stdout }}"
   
   - name: Adding log to file
     lineinfile:
      dest: exim.txt
      line: "\n \n  [ {{ server.stdout }} ] ------------------------------------------ \n \n {{ daxim.stdout }} \n \n"
#      state: present
     delegate_to: localhost
     when: daxim.stdout >= limit
